/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvInput {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled": boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el input vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Identificador estable del input nativo interno.
         */
        "inputId"?: string;
        /**
          * Sugerencia nativa de teclado virtual.
         */
        "inputMode"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required": boolean;
        /**
          * Tipo nativo del input.
          * @default 'text'
         */
        "type": 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        /**
          * Valor actual del input.
          * @default ''
         */
        "value": string;
    }
}
export interface IvInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvInputElement;
}
declare global {
    interface HTMLIvInputElementEventMap {
        "valueChange": string;
    }
    interface HTMLIvInputElement extends Components.IvInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvInputElementEventMap>(type: K, listener: (this: HTMLIvInputElement, ev: IvInputCustomEvent<HTMLIvInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvInputElementEventMap>(type: K, listener: (this: HTMLIvInputElement, ev: IvInputCustomEvent<HTMLIvInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvInputElement: {
        prototype: HTMLIvInputElement;
        new (): HTMLIvInputElement;
    };
    interface HTMLElementTagNameMap {
        "iv-input": HTMLIvInputElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface IvInput {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el input vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Identificador estable del input nativo interno.
         */
        "inputId"?: string;
        /**
          * Sugerencia nativa de teclado virtual.
         */
        "inputMode"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Se emite cuando cambia el valor desde el input nativo.
         */
        "onValueChange"?: (event: IvInputCustomEvent<string>) => void;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required"?: boolean;
        /**
          * Tipo nativo del input.
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        /**
          * Valor actual del input.
          * @default ''
         */
        "value"?: string;
    }

    interface IvInputAttributes {
        "label": string;
        "inputId": string;
        "value": string;
        "type": 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        "placeholder": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "name": string;
        "form": string;
        "autocomplete": string;
        "inputMode": string;
    }

    interface IntrinsicElements {
        "iv-input": Omit<IvInput, keyof IvInputAttributes> & { [K in keyof IvInput & keyof IvInputAttributes]?: IvInput[K] } & { [K in keyof IvInput & keyof IvInputAttributes as `attr:${K}`]?: IvInputAttributes[K] } & { [K in keyof IvInput & keyof IvInputAttributes as `prop:${K}`]?: IvInput[K] } & OneOf<"label", IvInput["label"], IvInputAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-input": LocalJSX.IntrinsicElements["iv-input"] & JSXBase.HTMLAttributes<HTMLIvInputElement>;
        }
    }
}
