/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IvDateRangePickerPart, IvDateRangePickerValueChangeDetail, IvDateRangePickerVariant } from "./components/molecules/iv-date-range-picker/iv-date-range-picker";
import { IvDialogCloseRequestDetail } from "./components/molecules/iv-dialog-close/iv-dialog-close";
import { IvIconName } from "./components/atoms/iv-icon/iv-icon";
export { IvDateRangePickerPart, IvDateRangePickerValueChangeDetail, IvDateRangePickerVariant } from "./components/molecules/iv-date-range-picker/iv-date-range-picker";
export { IvDialogCloseRequestDetail } from "./components/molecules/iv-dialog-close/iv-dialog-close";
export { IvIconName } from "./components/atoms/iv-icon/iv-icon";
export namespace Components {
    interface IvButton {
        /**
          * Identificador del elemento controlado por el boton.
         */
        "controls"?: string;
        /**
          * Marca un enlace como el item actual dentro de un conjunto.
         */
        "current"?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false';
        /**
          * Referencia al elemento que describe el control.
         */
        "describedBy"?: string;
        /**
          * Deshabilita la interaccion del control.
          * @default false
         */
        "disabled": boolean;
        /**
          * Estado expandido cuando el boton controla contenido desplegable.
         */
        "expanded"?: boolean;
        /**
          * Indica si el boton abre un popup y de que tipo.
         */
        "hasPopup"?: 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
        /**
          * Si se informa, el componente renderiza un enlace.
         */
        "href"?: string;
        /**
          * Nombre accesible cuando el contenido visible no describe suficientemente la accion.
         */
        "label"?: string;
        /**
          * Referencia al elemento que etiqueta el control.
         */
        "labelledBy"?: string;
        /**
          * Estado pulsado para botones tipo toggle.
         */
        "pressed"?: boolean | 'mixed';
        /**
          * Relacion del enlace cuando se usa `href`.
         */
        "rel"?: string;
        /**
          * Destino del enlace cuando se usa `href`.
         */
        "target"?: '_self' | '_blank' | '_parent' | '_top';
        /**
          * Tipo nativo del boton cuando no se renderiza como enlace.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Valor nativo del boton para formularios y dialog method="dialog".
         */
        "value"?: string;
        /**
          * Variante visual del boton.
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
    }
    interface IvDateRangePicker {
        /**
          * Cierra el calendario.
         */
        "close": () => Promise<void>;
        /**
          * Deshabilita todos los controles.
          * @default false
         */
        "disabled": boolean;
        /**
          * Etiqueta visible del campo final.
          * @default 'Hasta'
         */
        "endLabel": string;
        /**
          * Nombre nativo enviado para la fecha final.
         */
        "endName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo final.
          * @default ''
         */
        "endValue": string;
        /**
          * Mensaje de error visible asociado al grupo.
         */
        "error"?: string;
        /**
          * Dia inicial de la semana: 0 domingo, 1 lunes, ... 6 sabado.
          * @default 1
         */
        "firstDayOfWeek": number;
        /**
          * Identificador de formulario asociado cuando los inputs viven fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al grupo.
          * @default 'Formato: AAAA-MM-DD. Tambien puedes escribir las fechas manualmente.'
         */
        "hint": string;
        /**
          * Etiqueta visible del grupo de rango.
          * @default 'Rango de fechas'
         */
        "label": string;
        /**
          * Locale usado para textos de fechas del calendario.
          * @default 'es-ES'
         */
        "locale": string;
        /**
          * Fecha maxima seleccionable en formato ISO YYYY-MM-DD.
         */
        "max"?: string;
        /**
          * Fecha minima seleccionable en formato ISO YYYY-MM-DD.
         */
        "min"?: string;
        /**
          * Controla si el calendario esta abierto.
          * @default false
         */
        "open": boolean;
        /**
          * Identificador estable usado como base para los controles internos.
         */
        "pickerId"?: string;
        /**
          * Evita editar el rango sin deshabilitar la lectura ni el foco.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marca ambos campos como requeridos.
          * @default false
         */
        "required": boolean;
        /**
          * Mueve el foco al campo nativo indicado.
         */
        "setFocus": (part?: IvDateRangePickerPart) => Promise<void>;
        /**
          * Abre el calendario cuando la variante lo permite.
         */
        "show": () => Promise<void>;
        /**
          * Etiqueta visible del campo inicial.
          * @default 'Desde'
         */
        "startLabel": string;
        /**
          * Nombre nativo enviado para la fecha inicial.
         */
        "startName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo inicial.
          * @default ''
         */
        "startValue": string;
        /**
          * Variante mobile-first del selector.
          * @default 'sheet'
         */
        "variant": IvDateRangePickerVariant;
    }
    interface IvDialog {
        /**
          * Cierra el dialog usando `close()` nativo.
         */
        "close": (returnValue?: string) => Promise<void>;
        /**
          * Permite cerrar haciendo click en el backdrop del dialog modal.
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Permite cerrar con la tecla Escape usando el evento `cancel` nativo.
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Referencia al elemento que describe el dialog nativo.
         */
        "describedBy"?: string;
        /**
          * Rol ARIA aplicado al dialog nativo. Usa `alertdialog` para confirmaciones críticas.
          * @default 'dialog'
         */
        "dialogRole": 'dialog' | 'alertdialog';
        /**
          * Selector CSS del elemento que debe recibir foco inicial al abrir. Si no se informa, se respeta el comportamiento nativo/autofocus.
         */
        "initialFocus"?: string;
        /**
          * Nombre accesible aplicado al dialog nativo cuando no hay un titulo visible asociado.
         */
        "label"?: string;
        /**
          * Referencia al elemento que etiqueta el dialog nativo.
         */
        "labelledBy"?: string;
        /**
          * Usa `showModal()` cuando esta activo y `show()` cuando esta desactivado.
          * @default true
         */
        "modal": boolean;
        /**
          * Controla si el dialog esta abierto.
          * @default false
         */
        "open": boolean;
        /**
          * Devuelve el foco al invocador al cerrar. Desactivado por defecto para evitar falsos focos en mobile/AT.
          * @default false
         */
        "restoreFocus": boolean;
        /**
          * Valor opcional devuelto por el dialog al cerrar.
          * @default ''
         */
        "returnValue": string;
        /**
          * Abre el dialog usando `show()` nativo.
         */
        "show": () => Promise<void>;
        /**
          * Abre el dialog usando `showModal()` nativo.
         */
        "showModal": () => Promise<void>;
    }
    interface IvDialogClose {
        /**
          * Valor enviado al dialog cuando se solicita el cierre.
          * @default ''
         */
        "returnValue": string;
    }
    interface IvIcon {
        /**
          * Nombre accesible cuando el icono transmite significado por si mismo.
         */
        "label"?: string;
        /**
          * Nombre del icono a renderizar.
         */
        "name": IvIconName;
        /**
          * Tamano visual del icono.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface IvInput {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled": boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el input vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Identificador estable del input nativo interno.
         */
        "inputId"?: string;
        /**
          * Sugerencia nativa de teclado virtual.
         */
        "inputMode"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required": boolean;
        /**
          * Tipo nativo del input.
          * @default 'text'
         */
        "type": 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        /**
          * Valor actual del input.
          * @default ''
         */
        "value": string;
    }
    interface IvTextarea {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled": boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el textarea vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Longitud maxima permitida por el textarea nativo.
         */
        "maxLength"?: number;
        /**
          * Longitud minima permitida por el textarea nativo.
         */
        "minLength"?: number;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required": boolean;
        /**
          * Numero visible de filas del textarea.
          * @default 4
         */
        "rows": number;
        /**
          * Identificador estable del textarea nativo interno.
         */
        "textareaId"?: string;
        /**
          * Valor actual del textarea.
          * @default ''
         */
        "value": string;
        /**
          * Estrategia nativa de ajuste de linea al enviar formularios.
         */
        "wrap"?: 'soft' | 'hard' | 'off';
    }
}
export interface IvDateRangePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvDateRangePickerElement;
}
export interface IvDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvDialogElement;
}
export interface IvDialogCloseCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvDialogCloseElement;
}
export interface IvInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvInputElement;
}
export interface IvTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvTextareaElement;
}
declare global {
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLIvDateRangePickerElementEventMap {
        "valueChange": IvDateRangePickerValueChangeDetail;
        "openChange": boolean;
    }
    interface HTMLIvDateRangePickerElement extends Components.IvDateRangePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvDateRangePickerElementEventMap>(type: K, listener: (this: HTMLIvDateRangePickerElement, ev: IvDateRangePickerCustomEvent<HTMLIvDateRangePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvDateRangePickerElementEventMap>(type: K, listener: (this: HTMLIvDateRangePickerElement, ev: IvDateRangePickerCustomEvent<HTMLIvDateRangePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvDateRangePickerElement: {
        prototype: HTMLIvDateRangePickerElement;
        new (): HTMLIvDateRangePickerElement;
    };
    interface HTMLIvDialogElementEventMap {
        "ivOpen": void;
        "ivClose": { returnValue: string };
        "ivCancel": void;
    }
    interface HTMLIvDialogElement extends Components.IvDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvDialogElementEventMap>(type: K, listener: (this: HTMLIvDialogElement, ev: IvDialogCustomEvent<HTMLIvDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvDialogElementEventMap>(type: K, listener: (this: HTMLIvDialogElement, ev: IvDialogCustomEvent<HTMLIvDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvDialogElement: {
        prototype: HTMLIvDialogElement;
        new (): HTMLIvDialogElement;
    };
    interface HTMLIvDialogCloseElementEventMap {
        "ivDialogCloseRequest": IvDialogCloseRequestDetail;
    }
    interface HTMLIvDialogCloseElement extends Components.IvDialogClose, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvDialogCloseElementEventMap>(type: K, listener: (this: HTMLIvDialogCloseElement, ev: IvDialogCloseCustomEvent<HTMLIvDialogCloseElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvDialogCloseElementEventMap>(type: K, listener: (this: HTMLIvDialogCloseElement, ev: IvDialogCloseCustomEvent<HTMLIvDialogCloseElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvDialogCloseElement: {
        prototype: HTMLIvDialogCloseElement;
        new (): HTMLIvDialogCloseElement;
    };
    interface HTMLIvIconElement extends Components.IvIcon, HTMLStencilElement {
    }
    var HTMLIvIconElement: {
        prototype: HTMLIvIconElement;
        new (): HTMLIvIconElement;
    };
    interface HTMLIvInputElementEventMap {
        "valueChange": string;
    }
    interface HTMLIvInputElement extends Components.IvInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvInputElementEventMap>(type: K, listener: (this: HTMLIvInputElement, ev: IvInputCustomEvent<HTMLIvInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvInputElementEventMap>(type: K, listener: (this: HTMLIvInputElement, ev: IvInputCustomEvent<HTMLIvInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvInputElement: {
        prototype: HTMLIvInputElement;
        new (): HTMLIvInputElement;
    };
    interface HTMLIvTextareaElementEventMap {
        "valueChange": string;
    }
    interface HTMLIvTextareaElement extends Components.IvTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvTextareaElementEventMap>(type: K, listener: (this: HTMLIvTextareaElement, ev: IvTextareaCustomEvent<HTMLIvTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvTextareaElementEventMap>(type: K, listener: (this: HTMLIvTextareaElement, ev: IvTextareaCustomEvent<HTMLIvTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvTextareaElement: {
        prototype: HTMLIvTextareaElement;
        new (): HTMLIvTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "iv-button": HTMLIvButtonElement;
        "iv-date-range-picker": HTMLIvDateRangePickerElement;
        "iv-dialog": HTMLIvDialogElement;
        "iv-dialog-close": HTMLIvDialogCloseElement;
        "iv-icon": HTMLIvIconElement;
        "iv-input": HTMLIvInputElement;
        "iv-textarea": HTMLIvTextareaElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface IvButton {
        /**
          * Identificador del elemento controlado por el boton.
         */
        "controls"?: string;
        /**
          * Marca un enlace como el item actual dentro de un conjunto.
         */
        "current"?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false';
        /**
          * Referencia al elemento que describe el control.
         */
        "describedBy"?: string;
        /**
          * Deshabilita la interaccion del control.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Estado expandido cuando el boton controla contenido desplegable.
         */
        "expanded"?: boolean;
        /**
          * Indica si el boton abre un popup y de que tipo.
         */
        "hasPopup"?: 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
        /**
          * Si se informa, el componente renderiza un enlace.
         */
        "href"?: string;
        /**
          * Nombre accesible cuando el contenido visible no describe suficientemente la accion.
         */
        "label"?: string;
        /**
          * Referencia al elemento que etiqueta el control.
         */
        "labelledBy"?: string;
        /**
          * Estado pulsado para botones tipo toggle.
         */
        "pressed"?: boolean | 'mixed';
        /**
          * Relacion del enlace cuando se usa `href`.
         */
        "rel"?: string;
        /**
          * Destino del enlace cuando se usa `href`.
         */
        "target"?: '_self' | '_blank' | '_parent' | '_top';
        /**
          * Tipo nativo del boton cuando no se renderiza como enlace.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Valor nativo del boton para formularios y dialog method="dialog".
         */
        "value"?: string;
        /**
          * Variante visual del boton.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'danger';
    }
    interface IvDateRangePicker {
        /**
          * Deshabilita todos los controles.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Etiqueta visible del campo final.
          * @default 'Hasta'
         */
        "endLabel"?: string;
        /**
          * Nombre nativo enviado para la fecha final.
         */
        "endName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo final.
          * @default ''
         */
        "endValue"?: string;
        /**
          * Mensaje de error visible asociado al grupo.
         */
        "error"?: string;
        /**
          * Dia inicial de la semana: 0 domingo, 1 lunes, ... 6 sabado.
          * @default 1
         */
        "firstDayOfWeek"?: number;
        /**
          * Identificador de formulario asociado cuando los inputs viven fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al grupo.
          * @default 'Formato: AAAA-MM-DD. Tambien puedes escribir las fechas manualmente.'
         */
        "hint"?: string;
        /**
          * Etiqueta visible del grupo de rango.
          * @default 'Rango de fechas'
         */
        "label"?: string;
        /**
          * Locale usado para textos de fechas del calendario.
          * @default 'es-ES'
         */
        "locale"?: string;
        /**
          * Fecha maxima seleccionable en formato ISO YYYY-MM-DD.
         */
        "max"?: string;
        /**
          * Fecha minima seleccionable en formato ISO YYYY-MM-DD.
         */
        "min"?: string;
        /**
          * Se emite cuando se abre o cierra el calendario.
         */
        "onOpenChange"?: (event: IvDateRangePickerCustomEvent<boolean>) => void;
        /**
          * Se emite cuando cambia cualquiera de las fechas.
         */
        "onValueChange"?: (event: IvDateRangePickerCustomEvent<IvDateRangePickerValueChangeDetail>) => void;
        /**
          * Controla si el calendario esta abierto.
          * @default false
         */
        "open"?: boolean;
        /**
          * Identificador estable usado como base para los controles internos.
         */
        "pickerId"?: string;
        /**
          * Evita editar el rango sin deshabilitar la lectura ni el foco.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marca ambos campos como requeridos.
          * @default false
         */
        "required"?: boolean;
        /**
          * Etiqueta visible del campo inicial.
          * @default 'Desde'
         */
        "startLabel"?: string;
        /**
          * Nombre nativo enviado para la fecha inicial.
         */
        "startName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo inicial.
          * @default ''
         */
        "startValue"?: string;
        /**
          * Variante mobile-first del selector.
          * @default 'sheet'
         */
        "variant"?: IvDateRangePickerVariant;
    }
    interface IvDialog {
        /**
          * Permite cerrar haciendo click en el backdrop del dialog modal.
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Permite cerrar con la tecla Escape usando el evento `cancel` nativo.
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Referencia al elemento que describe el dialog nativo.
         */
        "describedBy"?: string;
        /**
          * Rol ARIA aplicado al dialog nativo. Usa `alertdialog` para confirmaciones críticas.
          * @default 'dialog'
         */
        "dialogRole"?: 'dialog' | 'alertdialog';
        /**
          * Selector CSS del elemento que debe recibir foco inicial al abrir. Si no se informa, se respeta el comportamiento nativo/autofocus.
         */
        "initialFocus"?: string;
        /**
          * Nombre accesible aplicado al dialog nativo cuando no hay un titulo visible asociado.
         */
        "label"?: string;
        /**
          * Referencia al elemento que etiqueta el dialog nativo.
         */
        "labelledBy"?: string;
        /**
          * Usa `showModal()` cuando esta activo y `show()` cuando esta desactivado.
          * @default true
         */
        "modal"?: boolean;
        /**
          * Se emite cuando el dialog recibe el evento nativo `cancel`.
         */
        "onIvCancel"?: (event: IvDialogCustomEvent<void>) => void;
        /**
          * Se emite cuando el dialog se cierra mediante la API nativa.
         */
        "onIvClose"?: (event: IvDialogCustomEvent<{ returnValue: string }>) => void;
        /**
          * Se emite cuando el dialog se abre mediante la API nativa.
         */
        "onIvOpen"?: (event: IvDialogCustomEvent<void>) => void;
        /**
          * Controla si el dialog esta abierto.
          * @default false
         */
        "open"?: boolean;
        /**
          * Devuelve el foco al invocador al cerrar. Desactivado por defecto para evitar falsos focos en mobile/AT.
          * @default false
         */
        "restoreFocus"?: boolean;
        /**
          * Valor opcional devuelto por el dialog al cerrar.
          * @default ''
         */
        "returnValue"?: string;
    }
    interface IvDialogClose {
        /**
          * Se emite cuando el contenido slotted solicita cerrar el dialog ancestro.
         */
        "onIvDialogCloseRequest"?: (event: IvDialogCloseCustomEvent<IvDialogCloseRequestDetail>) => void;
        /**
          * Valor enviado al dialog cuando se solicita el cierre.
          * @default ''
         */
        "returnValue"?: string;
    }
    interface IvIcon {
        /**
          * Nombre accesible cuando el icono transmite significado por si mismo.
         */
        "label"?: string;
        /**
          * Nombre del icono a renderizar.
         */
        "name": IvIconName;
        /**
          * Tamano visual del icono.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface IvInput {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el input vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Identificador estable del input nativo interno.
         */
        "inputId"?: string;
        /**
          * Sugerencia nativa de teclado virtual.
         */
        "inputMode"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Se emite cuando cambia el valor desde el input nativo.
         */
        "onValueChange"?: (event: IvInputCustomEvent<string>) => void;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required"?: boolean;
        /**
          * Tipo nativo del input.
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        /**
          * Valor actual del input.
          * @default ''
         */
        "value"?: string;
    }
    interface IvTextarea {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el textarea vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Longitud maxima permitida por el textarea nativo.
         */
        "maxLength"?: number;
        /**
          * Longitud minima permitida por el textarea nativo.
         */
        "minLength"?: number;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Se emite cuando cambia el valor desde el textarea nativo.
         */
        "onValueChange"?: (event: IvTextareaCustomEvent<string>) => void;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required"?: boolean;
        /**
          * Numero visible de filas del textarea.
          * @default 4
         */
        "rows"?: number;
        /**
          * Identificador estable del textarea nativo interno.
         */
        "textareaId"?: string;
        /**
          * Valor actual del textarea.
          * @default ''
         */
        "value"?: string;
        /**
          * Estrategia nativa de ajuste de linea al enviar formularios.
         */
        "wrap"?: 'soft' | 'hard' | 'off';
    }

    interface IvButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
        "type": 'button' | 'submit' | 'reset';
        "value": string;
        "disabled": boolean;
        "href": string;
        "target": '_self' | '_blank' | '_parent' | '_top';
        "rel": string;
        "label": string;
        "labelledBy": string;
        "describedBy": string;
        "controls": string;
        "expanded": boolean;
        "pressed": string;
        "hasPopup": 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
        "current": 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false';
    }
    interface IvDateRangePickerAttributes {
        "variant": IvDateRangePickerVariant;
        "label": string;
        "startLabel": string;
        "endLabel": string;
        "startValue": string;
        "endValue": string;
        "startName": string;
        "endName": string;
        "form": string;
        "min": string;
        "max": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "open": boolean;
        "locale": string;
        "firstDayOfWeek": number;
        "pickerId": string;
    }
    interface IvDialogAttributes {
        "open": boolean;
        "modal": boolean;
        "dialogRole": 'dialog' | 'alertdialog';
        "closeOnBackdrop": boolean;
        "closeOnEscape": boolean;
        "returnValue": string;
        "initialFocus": string;
        "restoreFocus": boolean;
        "label": string;
        "labelledBy": string;
        "describedBy": string;
    }
    interface IvDialogCloseAttributes {
        "returnValue": string;
    }
    interface IvIconAttributes {
        "name": IvIconName;
        "size": 'sm' | 'md' | 'lg';
        "label": string;
    }
    interface IvInputAttributes {
        "label": string;
        "inputId": string;
        "value": string;
        "type": 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        "placeholder": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "name": string;
        "form": string;
        "autocomplete": string;
        "inputMode": string;
    }
    interface IvTextareaAttributes {
        "label": string;
        "textareaId": string;
        "value": string;
        "placeholder": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "name": string;
        "form": string;
        "autocomplete": string;
        "rows": number;
        "maxLength": number;
        "minLength": number;
        "wrap": 'soft' | 'hard' | 'off';
    }

    interface IntrinsicElements {
        "iv-button": Omit<IvButton, keyof IvButtonAttributes> & { [K in keyof IvButton & keyof IvButtonAttributes]?: IvButton[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `attr:${K}`]?: IvButtonAttributes[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `prop:${K}`]?: IvButton[K] };
        "iv-date-range-picker": Omit<IvDateRangePicker, keyof IvDateRangePickerAttributes> & { [K in keyof IvDateRangePicker & keyof IvDateRangePickerAttributes]?: IvDateRangePicker[K] } & { [K in keyof IvDateRangePicker & keyof IvDateRangePickerAttributes as `attr:${K}`]?: IvDateRangePickerAttributes[K] } & { [K in keyof IvDateRangePicker & keyof IvDateRangePickerAttributes as `prop:${K}`]?: IvDateRangePicker[K] };
        "iv-dialog": Omit<IvDialog, keyof IvDialogAttributes> & { [K in keyof IvDialog & keyof IvDialogAttributes]?: IvDialog[K] } & { [K in keyof IvDialog & keyof IvDialogAttributes as `attr:${K}`]?: IvDialogAttributes[K] } & { [K in keyof IvDialog & keyof IvDialogAttributes as `prop:${K}`]?: IvDialog[K] };
        "iv-dialog-close": Omit<IvDialogClose, keyof IvDialogCloseAttributes> & { [K in keyof IvDialogClose & keyof IvDialogCloseAttributes]?: IvDialogClose[K] } & { [K in keyof IvDialogClose & keyof IvDialogCloseAttributes as `attr:${K}`]?: IvDialogCloseAttributes[K] } & { [K in keyof IvDialogClose & keyof IvDialogCloseAttributes as `prop:${K}`]?: IvDialogClose[K] };
        "iv-icon": Omit<IvIcon, keyof IvIconAttributes> & { [K in keyof IvIcon & keyof IvIconAttributes]?: IvIcon[K] } & { [K in keyof IvIcon & keyof IvIconAttributes as `attr:${K}`]?: IvIconAttributes[K] } & { [K in keyof IvIcon & keyof IvIconAttributes as `prop:${K}`]?: IvIcon[K] } & OneOf<"name", IvIcon["name"], IvIconAttributes["name"]>;
        "iv-input": Omit<IvInput, keyof IvInputAttributes> & { [K in keyof IvInput & keyof IvInputAttributes]?: IvInput[K] } & { [K in keyof IvInput & keyof IvInputAttributes as `attr:${K}`]?: IvInputAttributes[K] } & { [K in keyof IvInput & keyof IvInputAttributes as `prop:${K}`]?: IvInput[K] } & OneOf<"label", IvInput["label"], IvInputAttributes["label"]>;
        "iv-textarea": Omit<IvTextarea, keyof IvTextareaAttributes> & { [K in keyof IvTextarea & keyof IvTextareaAttributes]?: IvTextarea[K] } & { [K in keyof IvTextarea & keyof IvTextareaAttributes as `attr:${K}`]?: IvTextareaAttributes[K] } & { [K in keyof IvTextarea & keyof IvTextareaAttributes as `prop:${K}`]?: IvTextarea[K] } & OneOf<"label", IvTextarea["label"], IvTextareaAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-button": LocalJSX.IntrinsicElements["iv-button"] & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
            "iv-date-range-picker": LocalJSX.IntrinsicElements["iv-date-range-picker"] & JSXBase.HTMLAttributes<HTMLIvDateRangePickerElement>;
            "iv-dialog": LocalJSX.IntrinsicElements["iv-dialog"] & JSXBase.HTMLAttributes<HTMLIvDialogElement>;
            "iv-dialog-close": LocalJSX.IntrinsicElements["iv-dialog-close"] & JSXBase.HTMLAttributes<HTMLIvDialogCloseElement>;
            "iv-icon": LocalJSX.IntrinsicElements["iv-icon"] & JSXBase.HTMLAttributes<HTMLIvIconElement>;
            "iv-input": LocalJSX.IntrinsicElements["iv-input"] & JSXBase.HTMLAttributes<HTMLIvInputElement>;
            "iv-textarea": LocalJSX.IntrinsicElements["iv-textarea"] & JSXBase.HTMLAttributes<HTMLIvTextareaElement>;
        }
    }
}
