/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvDialog {
        /**
          * Cierra el dialog usando `close()` nativo.
         */
        "close": (returnValue?: string) => Promise<void>;
        /**
          * Permite cerrar haciendo click en el backdrop del dialog modal.
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Permite cerrar con la tecla Escape usando el evento `cancel` nativo.
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Referencia al elemento que describe el dialog nativo.
         */
        "describedBy"?: string;
        /**
          * Rol ARIA aplicado al dialog nativo. Usa `alertdialog` para confirmaciones críticas.
          * @default 'dialog'
         */
        "dialogRole": 'dialog' | 'alertdialog';
        /**
          * Selector CSS del elemento que debe recibir foco inicial al abrir. Si no se informa, se respeta el comportamiento nativo/autofocus.
         */
        "initialFocus"?: string;
        /**
          * Nombre accesible aplicado al dialog nativo cuando no hay un titulo visible asociado.
         */
        "label"?: string;
        /**
          * Referencia al elemento que etiqueta el dialog nativo.
         */
        "labelledBy"?: string;
        /**
          * Usa `showModal()` cuando esta activo y `show()` cuando esta desactivado.
          * @default true
         */
        "modal": boolean;
        /**
          * Controla si el dialog esta abierto.
          * @default false
         */
        "open": boolean;
        /**
          * Devuelve el foco al invocador al cerrar. Desactivado por defecto para evitar falsos focos en mobile/AT.
          * @default false
         */
        "restoreFocus": boolean;
        /**
          * Valor opcional devuelto por el dialog al cerrar.
          * @default ''
         */
        "returnValue": string;
        /**
          * Abre el dialog usando `show()` nativo.
         */
        "show": () => Promise<void>;
        /**
          * Abre el dialog usando `showModal()` nativo.
         */
        "showModal": () => Promise<void>;
    }
}
export interface IvDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvDialogElement;
}
declare global {
    interface HTMLIvDialogElementEventMap {
        "ivOpen": void;
        "ivClose": { returnValue: string };
        "ivCancel": void;
    }
    interface HTMLIvDialogElement extends Components.IvDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvDialogElementEventMap>(type: K, listener: (this: HTMLIvDialogElement, ev: IvDialogCustomEvent<HTMLIvDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvDialogElementEventMap>(type: K, listener: (this: HTMLIvDialogElement, ev: IvDialogCustomEvent<HTMLIvDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvDialogElement: {
        prototype: HTMLIvDialogElement;
        new (): HTMLIvDialogElement;
    };
    interface HTMLElementTagNameMap {
        "iv-dialog": HTMLIvDialogElement;
    }
}
declare namespace LocalJSX {
    interface IvDialog {
        /**
          * Permite cerrar haciendo click en el backdrop del dialog modal.
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Permite cerrar con la tecla Escape usando el evento `cancel` nativo.
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Referencia al elemento que describe el dialog nativo.
         */
        "describedBy"?: string;
        /**
          * Rol ARIA aplicado al dialog nativo. Usa `alertdialog` para confirmaciones críticas.
          * @default 'dialog'
         */
        "dialogRole"?: 'dialog' | 'alertdialog';
        /**
          * Selector CSS del elemento que debe recibir foco inicial al abrir. Si no se informa, se respeta el comportamiento nativo/autofocus.
         */
        "initialFocus"?: string;
        /**
          * Nombre accesible aplicado al dialog nativo cuando no hay un titulo visible asociado.
         */
        "label"?: string;
        /**
          * Referencia al elemento que etiqueta el dialog nativo.
         */
        "labelledBy"?: string;
        /**
          * Usa `showModal()` cuando esta activo y `show()` cuando esta desactivado.
          * @default true
         */
        "modal"?: boolean;
        /**
          * Se emite cuando el dialog recibe el evento nativo `cancel`.
         */
        "onIvCancel"?: (event: IvDialogCustomEvent<void>) => void;
        /**
          * Se emite cuando el dialog se cierra mediante la API nativa.
         */
        "onIvClose"?: (event: IvDialogCustomEvent<{ returnValue: string }>) => void;
        /**
          * Se emite cuando el dialog se abre mediante la API nativa.
         */
        "onIvOpen"?: (event: IvDialogCustomEvent<void>) => void;
        /**
          * Controla si el dialog esta abierto.
          * @default false
         */
        "open"?: boolean;
        /**
          * Devuelve el foco al invocador al cerrar. Desactivado por defecto para evitar falsos focos en mobile/AT.
          * @default false
         */
        "restoreFocus"?: boolean;
        /**
          * Valor opcional devuelto por el dialog al cerrar.
          * @default ''
         */
        "returnValue"?: string;
    }

    interface IvDialogAttributes {
        "open": boolean;
        "modal": boolean;
        "dialogRole": 'dialog' | 'alertdialog';
        "closeOnBackdrop": boolean;
        "closeOnEscape": boolean;
        "returnValue": string;
        "initialFocus": string;
        "restoreFocus": boolean;
        "label": string;
        "labelledBy": string;
        "describedBy": string;
    }

    interface IntrinsicElements {
        "iv-dialog": Omit<IvDialog, keyof IvDialogAttributes> & { [K in keyof IvDialog & keyof IvDialogAttributes]?: IvDialog[K] } & { [K in keyof IvDialog & keyof IvDialogAttributes as `attr:${K}`]?: IvDialogAttributes[K] } & { [K in keyof IvDialog & keyof IvDialogAttributes as `prop:${K}`]?: IvDialog[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-dialog": LocalJSX.IntrinsicElements["iv-dialog"] & JSXBase.HTMLAttributes<HTMLIvDialogElement>;
        }
    }
}
