/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvTextarea {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled": boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el textarea vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Longitud maxima permitida por el textarea nativo.
         */
        "maxLength"?: number;
        /**
          * Longitud minima permitida por el textarea nativo.
         */
        "minLength"?: number;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required": boolean;
        /**
          * Numero visible de filas del textarea.
          * @default 4
         */
        "rows": number;
        /**
          * Identificador estable del textarea nativo interno.
         */
        "textareaId"?: string;
        /**
          * Valor actual del textarea.
          * @default ''
         */
        "value": string;
        /**
          * Estrategia nativa de ajuste de linea al enviar formularios.
         */
        "wrap"?: 'soft' | 'hard' | 'off';
    }
}
export interface IvTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvTextareaElement;
}
declare global {
    interface HTMLIvTextareaElementEventMap {
        "valueChange": string;
    }
    interface HTMLIvTextareaElement extends Components.IvTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvTextareaElementEventMap>(type: K, listener: (this: HTMLIvTextareaElement, ev: IvTextareaCustomEvent<HTMLIvTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvTextareaElementEventMap>(type: K, listener: (this: HTMLIvTextareaElement, ev: IvTextareaCustomEvent<HTMLIvTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvTextareaElement: {
        prototype: HTMLIvTextareaElement;
        new (): HTMLIvTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "iv-textarea": HTMLIvTextareaElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface IvTextarea {
        /**
          * Sugerencia nativa de autocompletado.
         */
        "autocomplete"?: string;
        /**
          * Deshabilita la interaccion del campo.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Mensaje de error visible asociado al campo.
         */
        "error"?: string;
        /**
          * Identificador de formulario asociado cuando el textarea vive fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al campo.
         */
        "hint"?: string;
        /**
          * Etiqueta visible del campo.
         */
        "label": string;
        /**
          * Longitud maxima permitida por el textarea nativo.
         */
        "maxLength"?: number;
        /**
          * Longitud minima permitida por el textarea nativo.
         */
        "minLength"?: number;
        /**
          * Nombre nativo enviado en formularios.
         */
        "name"?: string;
        /**
          * Se emite cuando cambia el valor desde el textarea nativo.
         */
        "onValueChange"?: (event: IvTextareaCustomEvent<string>) => void;
        /**
          * Texto auxiliar cuando el campo esta vacio.
         */
        "placeholder"?: string;
        /**
          * Evita editar el valor sin deshabilitar el foco.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marca el campo como requerido.
          * @default false
         */
        "required"?: boolean;
        /**
          * Numero visible de filas del textarea.
          * @default 4
         */
        "rows"?: number;
        /**
          * Identificador estable del textarea nativo interno.
         */
        "textareaId"?: string;
        /**
          * Valor actual del textarea.
          * @default ''
         */
        "value"?: string;
        /**
          * Estrategia nativa de ajuste de linea al enviar formularios.
         */
        "wrap"?: 'soft' | 'hard' | 'off';
    }

    interface IvTextareaAttributes {
        "label": string;
        "textareaId": string;
        "value": string;
        "placeholder": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "name": string;
        "form": string;
        "autocomplete": string;
        "rows": number;
        "maxLength": number;
        "minLength": number;
        "wrap": 'soft' | 'hard' | 'off';
    }

    interface IntrinsicElements {
        "iv-textarea": Omit<IvTextarea, keyof IvTextareaAttributes> & { [K in keyof IvTextarea & keyof IvTextareaAttributes]?: IvTextarea[K] } & { [K in keyof IvTextarea & keyof IvTextareaAttributes as `attr:${K}`]?: IvTextareaAttributes[K] } & { [K in keyof IvTextarea & keyof IvTextareaAttributes as `prop:${K}`]?: IvTextarea[K] } & OneOf<"label", IvTextarea["label"], IvTextareaAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-textarea": LocalJSX.IntrinsicElements["iv-textarea"] & JSXBase.HTMLAttributes<HTMLIvTextareaElement>;
        }
    }
}
