/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IvIconName } from "./components/iv-icon/iv-icon";
export { IvIconName } from "./components/iv-icon/iv-icon";
export namespace Components {
    interface IvIcon {
        /**
          * Nombre accesible cuando el icono transmite significado por si mismo.
         */
        "label"?: string;
        /**
          * Nombre del icono a renderizar.
         */
        "name": IvIconName;
        /**
          * Tamano visual del icono.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
declare global {
    interface HTMLIvIconElement extends Components.IvIcon, HTMLStencilElement {
    }
    var HTMLIvIconElement: {
        prototype: HTMLIvIconElement;
        new (): HTMLIvIconElement;
    };
    interface HTMLElementTagNameMap {
        "iv-icon": HTMLIvIconElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface IvIcon {
        /**
          * Nombre accesible cuando el icono transmite significado por si mismo.
         */
        "label"?: string;
        /**
          * Nombre del icono a renderizar.
         */
        "name": IvIconName;
        /**
          * Tamano visual del icono.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }

    interface IvIconAttributes {
        "name": IvIconName;
        "size": 'sm' | 'md' | 'lg';
        "label": string;
    }

    interface IntrinsicElements {
        "iv-icon": Omit<IvIcon, keyof IvIconAttributes> & { [K in keyof IvIcon & keyof IvIconAttributes]?: IvIcon[K] } & { [K in keyof IvIcon & keyof IvIconAttributes as `attr:${K}`]?: IvIconAttributes[K] } & { [K in keyof IvIcon & keyof IvIconAttributes as `prop:${K}`]?: IvIcon[K] } & OneOf<"name", IvIcon["name"], IvIconAttributes["name"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-icon": LocalJSX.IntrinsicElements["iv-icon"] & JSXBase.HTMLAttributes<HTMLIvIconElement>;
        }
    }
}
