/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvButton {
        /**
          * Identificador del elemento controlado por el boton.
         */
        "ariaControls"?: string;
        /**
          * Marca un enlace como el item actual dentro de un conjunto.
         */
        "ariaCurrent"?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false';
        /**
          * Referencia al elemento que describe el control.
         */
        "ariaDescribedby"?: string;
        /**
          * Estado expandido cuando el boton controla contenido desplegable.
         */
        "ariaExpanded"?: boolean;
        /**
          * Indica si el boton abre un popup y de que tipo.
         */
        "ariaHaspopup"?: 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
        /**
          * Nombre accesible cuando el contenido visible no describe suficientemente la accion.
         */
        "ariaLabel"?: string;
        /**
          * Referencia al elemento que etiqueta el control.
         */
        "ariaLabelledby"?: string;
        /**
          * Estado pulsado para botones tipo toggle.
         */
        "ariaPressed"?: boolean | 'mixed';
        /**
          * Deshabilita la interaccion del control.
          * @default false
         */
        "disabled": boolean;
        /**
          * Si se informa, el componente renderiza un enlace.
         */
        "href"?: string;
        /**
          * Relacion del enlace cuando se usa `href`.
         */
        "rel"?: string;
        /**
          * Destino del enlace cuando se usa `href`.
         */
        "target"?: '_self' | '_blank' | '_parent' | '_top';
        /**
          * Tipo nativo del boton cuando no se renderiza como enlace.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Variante visual del boton.
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ghost';
    }
}
declare global {
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLElementTagNameMap {
        "iv-button": HTMLIvButtonElement;
    }
}
declare namespace LocalJSX {
    interface IvButton {
        /**
          * Identificador del elemento controlado por el boton.
         */
        "ariaControls"?: string;
        /**
          * Marca un enlace como el item actual dentro de un conjunto.
         */
        "ariaCurrent"?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false';
        /**
          * Referencia al elemento que describe el control.
         */
        "ariaDescribedby"?: string;
        /**
          * Estado expandido cuando el boton controla contenido desplegable.
         */
        "ariaExpanded"?: boolean;
        /**
          * Indica si el boton abre un popup y de que tipo.
         */
        "ariaHaspopup"?: 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
        /**
          * Nombre accesible cuando el contenido visible no describe suficientemente la accion.
         */
        "ariaLabel"?: string;
        /**
          * Referencia al elemento que etiqueta el control.
         */
        "ariaLabelledby"?: string;
        /**
          * Estado pulsado para botones tipo toggle.
         */
        "ariaPressed"?: boolean | 'mixed';
        /**
          * Deshabilita la interaccion del control.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Si se informa, el componente renderiza un enlace.
         */
        "href"?: string;
        /**
          * Relacion del enlace cuando se usa `href`.
         */
        "rel"?: string;
        /**
          * Destino del enlace cuando se usa `href`.
         */
        "target"?: '_self' | '_blank' | '_parent' | '_top';
        /**
          * Tipo nativo del boton cuando no se renderiza como enlace.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Variante visual del boton.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost';
    }

    interface IvButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost';
        "type": 'button' | 'submit' | 'reset';
        "disabled": boolean;
        "href": string;
        "target": '_self' | '_blank' | '_parent' | '_top';
        "rel": string;
        "ariaLabel": string;
        "ariaLabelledby": string;
        "ariaDescribedby": string;
        "ariaControls": string;
        "ariaExpanded": boolean;
        "ariaPressed": string;
        "ariaHaspopup": 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
        "ariaCurrent": 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false';
    }

    interface IntrinsicElements {
        "iv-button": Omit<IvButton, keyof IvButtonAttributes> & { [K in keyof IvButton & keyof IvButtonAttributes]?: IvButton[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `attr:${K}`]?: IvButtonAttributes[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `prop:${K}`]?: IvButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-button": LocalJSX.IntrinsicElements["iv-button"] & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
        }
    }
}
