/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvButton {
        /**
          * Deshabilita la interaccion del control.
          * @default false
         */
        "disabled": boolean;
        /**
          * Si se informa, el componente renderiza un enlace.
         */
        "href"?: string;
        /**
          * Variante visual del boton.
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ghost';
    }
}
declare global {
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLElementTagNameMap {
        "iv-button": HTMLIvButtonElement;
    }
}
declare namespace LocalJSX {
    interface IvButton {
        /**
          * Deshabilita la interaccion del control.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Si se informa, el componente renderiza un enlace.
         */
        "href"?: string;
        /**
          * Variante visual del boton.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost';
    }

    interface IvButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost';
        "disabled": boolean;
        "href": string;
    }

    interface IntrinsicElements {
        "iv-button": Omit<IvButton, keyof IvButtonAttributes> & { [K in keyof IvButton & keyof IvButtonAttributes]?: IvButton[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `attr:${K}`]?: IvButtonAttributes[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `prop:${K}`]?: IvButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-button": LocalJSX.IntrinsicElements["iv-button"] & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
        }
    }
}
