/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IvDateRangePickerPart, IvDateRangePickerValueChangeDetail, IvDateRangePickerVariant } from "./components/iv-date-range-picker/iv-date-range-picker";
export { IvDateRangePickerPart, IvDateRangePickerValueChangeDetail, IvDateRangePickerVariant } from "./components/iv-date-range-picker/iv-date-range-picker";
export namespace Components {
    interface IvDateRangePicker {
        /**
          * Cierra el calendario.
         */
        "close": () => Promise<void>;
        /**
          * Deshabilita todos los controles.
          * @default false
         */
        "disabled": boolean;
        /**
          * Etiqueta visible del campo final.
          * @default 'Hasta'
         */
        "endLabel": string;
        /**
          * Nombre nativo enviado para la fecha final.
         */
        "endName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo final.
          * @default ''
         */
        "endValue": string;
        /**
          * Mensaje de error visible asociado al grupo.
         */
        "error"?: string;
        /**
          * Dia inicial de la semana: 0 domingo, 1 lunes, ... 6 sabado.
          * @default 1
         */
        "firstDayOfWeek": number;
        /**
          * Identificador de formulario asociado cuando los inputs viven fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al grupo.
          * @default 'Formato: AAAA-MM-DD. Tambien puedes escribir las fechas manualmente.'
         */
        "hint": string;
        /**
          * Etiqueta visible del grupo de rango.
          * @default 'Rango de fechas'
         */
        "label": string;
        /**
          * Locale usado para textos de fechas del calendario.
          * @default 'es-ES'
         */
        "locale": string;
        /**
          * Fecha maxima seleccionable en formato ISO YYYY-MM-DD.
         */
        "max"?: string;
        /**
          * Fecha minima seleccionable en formato ISO YYYY-MM-DD.
         */
        "min"?: string;
        /**
          * Controla si el calendario esta abierto.
          * @default false
         */
        "open": boolean;
        /**
          * Identificador estable usado como base para los controles internos.
         */
        "pickerId"?: string;
        /**
          * Evita editar el rango sin deshabilitar la lectura ni el foco.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marca ambos campos como requeridos.
          * @default false
         */
        "required": boolean;
        /**
          * Mueve el foco al campo nativo indicado.
         */
        "setFocus": (part?: IvDateRangePickerPart) => Promise<void>;
        /**
          * Abre el calendario cuando la variante lo permite.
         */
        "show": () => Promise<void>;
        /**
          * Etiqueta visible del campo inicial.
          * @default 'Desde'
         */
        "startLabel": string;
        /**
          * Nombre nativo enviado para la fecha inicial.
         */
        "startName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo inicial.
          * @default ''
         */
        "startValue": string;
        /**
          * Variante mobile-first del selector.
          * @default 'sheet'
         */
        "variant": IvDateRangePickerVariant;
    }
}
export interface IvDateRangePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvDateRangePickerElement;
}
declare global {
    interface HTMLIvDateRangePickerElementEventMap {
        "valueChange": IvDateRangePickerValueChangeDetail;
        "openChange": boolean;
    }
    interface HTMLIvDateRangePickerElement extends Components.IvDateRangePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvDateRangePickerElementEventMap>(type: K, listener: (this: HTMLIvDateRangePickerElement, ev: IvDateRangePickerCustomEvent<HTMLIvDateRangePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvDateRangePickerElementEventMap>(type: K, listener: (this: HTMLIvDateRangePickerElement, ev: IvDateRangePickerCustomEvent<HTMLIvDateRangePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvDateRangePickerElement: {
        prototype: HTMLIvDateRangePickerElement;
        new (): HTMLIvDateRangePickerElement;
    };
    interface HTMLElementTagNameMap {
        "iv-date-range-picker": HTMLIvDateRangePickerElement;
    }
}
declare namespace LocalJSX {
    interface IvDateRangePicker {
        /**
          * Deshabilita todos los controles.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Etiqueta visible del campo final.
          * @default 'Hasta'
         */
        "endLabel"?: string;
        /**
          * Nombre nativo enviado para la fecha final.
         */
        "endName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo final.
          * @default ''
         */
        "endValue"?: string;
        /**
          * Mensaje de error visible asociado al grupo.
         */
        "error"?: string;
        /**
          * Dia inicial de la semana: 0 domingo, 1 lunes, ... 6 sabado.
          * @default 1
         */
        "firstDayOfWeek"?: number;
        /**
          * Identificador de formulario asociado cuando los inputs viven fuera del form.
         */
        "form"?: string;
        /**
          * Ayuda visible asociada al grupo.
          * @default 'Formato: AAAA-MM-DD. Tambien puedes escribir las fechas manualmente.'
         */
        "hint"?: string;
        /**
          * Etiqueta visible del grupo de rango.
          * @default 'Rango de fechas'
         */
        "label"?: string;
        /**
          * Locale usado para textos de fechas del calendario.
          * @default 'es-ES'
         */
        "locale"?: string;
        /**
          * Fecha maxima seleccionable en formato ISO YYYY-MM-DD.
         */
        "max"?: string;
        /**
          * Fecha minima seleccionable en formato ISO YYYY-MM-DD.
         */
        "min"?: string;
        /**
          * Se emite cuando se abre o cierra el calendario.
         */
        "onOpenChange"?: (event: IvDateRangePickerCustomEvent<boolean>) => void;
        /**
          * Se emite cuando cambia cualquiera de las fechas.
         */
        "onValueChange"?: (event: IvDateRangePickerCustomEvent<IvDateRangePickerValueChangeDetail>) => void;
        /**
          * Controla si el calendario esta abierto.
          * @default false
         */
        "open"?: boolean;
        /**
          * Identificador estable usado como base para los controles internos.
         */
        "pickerId"?: string;
        /**
          * Evita editar el rango sin deshabilitar la lectura ni el foco.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marca ambos campos como requeridos.
          * @default false
         */
        "required"?: boolean;
        /**
          * Etiqueta visible del campo inicial.
          * @default 'Desde'
         */
        "startLabel"?: string;
        /**
          * Nombre nativo enviado para la fecha inicial.
         */
        "startName"?: string;
        /**
          * Valor ISO YYYY-MM-DD del campo inicial.
          * @default ''
         */
        "startValue"?: string;
        /**
          * Variante mobile-first del selector.
          * @default 'sheet'
         */
        "variant"?: IvDateRangePickerVariant;
    }

    interface IvDateRangePickerAttributes {
        "variant": IvDateRangePickerVariant;
        "label": string;
        "startLabel": string;
        "endLabel": string;
        "startValue": string;
        "endValue": string;
        "startName": string;
        "endName": string;
        "form": string;
        "min": string;
        "max": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "open": boolean;
        "locale": string;
        "firstDayOfWeek": number;
        "pickerId": string;
    }

    interface IntrinsicElements {
        "iv-date-range-picker": Omit<IvDateRangePicker, keyof IvDateRangePickerAttributes> & { [K in keyof IvDateRangePicker & keyof IvDateRangePickerAttributes]?: IvDateRangePicker[K] } & { [K in keyof IvDateRangePicker & keyof IvDateRangePickerAttributes as `attr:${K}`]?: IvDateRangePickerAttributes[K] } & { [K in keyof IvDateRangePicker & keyof IvDateRangePickerAttributes as `prop:${K}`]?: IvDateRangePicker[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-date-range-picker": LocalJSX.IntrinsicElements["iv-date-range-picker"] & JSXBase.HTMLAttributes<HTMLIvDateRangePickerElement>;
        }
    }
}
